Document: visiweather
Title: Debian visiweather Manual
Author: <insert document author here>
Abstract: This manual describes what visiweather is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/visiweather/visiweather.sgml.gz

Format: postscript
Files: /usr/share/doc/visiweather/visiweather.ps.gz

Format: text
Files: /usr/share/doc/visiweather/visiweather.text.gz

Format: HTML
Index: /usr/share/doc/visiweather/html/index.html
Files: /usr/share/doc/visiweather/html/*.html


